apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"cloudsqlproxy","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"cloudsqlproxy"}},"spec":{"containers":[{"command":["/cloud_sql_proxy","-dir=/cloudsql","-instances=dublin-coach-123:europe-west2:dublin-coach-db=tcp:0.0.0.0:3307","-credential_file=/credentials/credentials.json"],"image":"b.gcr.io/cloudsql-docker/gce-proxy:latest","imagePullPolicy":"Always","name":"cloudsqlproxy","ports":[{"containerPort":3306,"name":"port-database"}],"volumeMounts":[{"mountPath":"/cloudsql","name":"cloudsql"},{"mountPath":"/credentials","name":"service-account-token"}]}],"volumes":[{"emptyDir":null,"name":"cloudsql"},{"name":"service-account-token","secret":{"secretName":"service-account-token"}}]}}}}
  creationTimestamp: 2018-01-23T15:53:58Z
  generation: 2
  labels:
    app: cloudsqlproxy
  name: cloudsqlproxy
  namespace: default
  resourceVersion: "4432728"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/cloudsqlproxy
  uid: 9fb39874-0055-11e8-8307-42010af00188
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsqlproxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloudsqlproxy
    spec:
      containers:
      - command:
        - /cloud_sql_proxy
        - -dir=/cloudsql
        - -instances=dublin-coach-123:europe-west2:dublin-coach-db=tcp:0.0.0.0:3306
        - -credential_file=/credentials/credentials.json
        image: b.gcr.io/cloudsql-docker/gce-proxy:latest
        imagePullPolicy: Always
        name: cloudsqlproxy
        ports:
        - containerPort: 3306
          name: port-database
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cloudsql
          name: cloudsql
        - mountPath: /credentials
          name: service-account-token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cloudsql
      - name: service-account-token
        secret:
          defaultMode: 420
          secretName: service-account-token
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-01-23T15:53:58Z
    lastUpdateTime: 2018-01-23T15:53:58Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1